import type { Metadata } from "next";
import localFont from "next/font/local";
import "./style.css";

const myFonts = localFont({
  src: "../fonts/BergenText-Bold.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFonts.className} bg-white overflow-y-scroll overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
